### model
model_name_or_path: /primus_datasets/models/Qwen2.5-VL-7B-Instruct
image_max_pixels: 3211264 # 262144 * 14 * 14(4096 tokens)
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: android_control-v2_jedi_train
template: qwen2_vl
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 32 # 和GPU保持一致吧
dataloader_num_workers: 16

### output
output_dir: /primus_oss/save_checkpoint/
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
##注意调整这俩参数，控制gbs
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
flash_attn: fa2
enable_liger_kernel: True

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
